---

  - name: DEPLOY & RESTORE CONFIGS
    hosts: iosxe,eos
    connection: local
    gather_facts: no

    tasks:

      - name: DEPLOY CONFIGURATIONS
        napalm_install_config:
          provider: "{{ connection_details }}"
          config_file: ./backups/{{ inventory_hostname }}.cfg
          replace_config: true
          commit_changes: true
          dev_os: "{{ ansible_network_os }}"
